title: DisMech
description: Open Source Codebase to simulate the dynamics of soft structures based on Discrete Differential Geometry methods
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  Matlab_url: https://github.com/Radha-Lahoti/DER-Matlab-MultiRod
  Cplus_url: https://github.com/StructuresComp/dismech-rods
  team_url: https://radha-ucla.github.io/Dismech_Cayman/Contributors.html
  theory_url: 
